version: "3.4"
services:
  beacon-chain:
    image: "beacon-chain.prysm-pyrmont.dnp.dappnode.eth:1.0.0"
    build:
      context: beacon-chain
      args:
        UPSTREAM_VERSION: v1.0.0-beta.3
    volumes:
      - "beacon-chain-data:/data"
    ports:
      - "13000"
      - "12000"
    restart: always
    environment:
      HTTP_WEB3PROVIDER: "http://goerli-geth.dappnode:8545"
      EXTRA_OPTS: ""
  validator:
    image: "validator.prysm-pyrmont.dnp.dappnode.eth:1.0.0"
    build:
      context: validator
      args:
        UPSTREAM_VERSION: v1.0.0-beta.0
    volumes:
      - "validator-data:/root/"
    ports:
      - "8000:80"
    restart: always
    environment:
      BEACON_RPC_PROVIDER: "beacon-chain:4000"
      BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
      WALLET_PASSWORD: my-password
volumes:
  beacon-chain-data: {}
  validator-data: {}
  validators: {}
  wallet-passwords: {}
