{
 "title": "DAppNode ETH2 Prysm-Pyrmont",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "package", "query": "prysm-pyrmont.dnp.dappnode.eth" },
   {
    "name": "service_validator",
    "query": "validator.prysm-pyrmont.dappnode"
   },
   {
    "name": "service_beacon_chain",
    "query": "beacon-chain.prysm-pyrmont.dappnode"
   }
  ]
 },
 "panels": [
  {
   "title": "DAppNode Prysm Validator",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Earnings",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Balance",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Total earnings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "sum(validator_balance{package=\"$package\"})-count(validator_balance{package=\"$package\"}>10)*32",
     "legendFormat": "Total balance"
    }
   ]
  },
  {
   "title": "Balances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_balance{package=\"$package\"} > 0 , \"pubkey\", \"$1\", \"pubkey\", \"(0x.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "ALERTS",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{package=\"$package\"})-(count(validator_balance{package=\"$package\"}>16)*32)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(validator_balance{package=\"$package\"})"
    }
   ]
  },
  { "type": "alertlist", "gridPos": { "h": 13, "w": 4, "x": 20, "y": 2 } },
  {
   "title": "Measured",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Projected",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hourly",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(validator_balance{package=\"$package\"}[1h]))"
    }
   ]
  },
  {
   "title": "Hourly",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((predict_linear(validator_balance{package=\"$package\"}[1h], 3600) and validator_statuses{package=\"$package\"}>2)) - sum(validator_balance{package=\"$package\"})"
    }
   ]
  },
  {
   "title": "Daily earnings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(validator_balance{package=\"$package\"}[1d])*3600*24)",
     "legendFormat": "Projected"
    },
    {
     "expr": "(sum((validator_balance{package=\"$package\"} and validator_balance{package=\"$package\"} > 10)) - count(validator_balance{package=\"$package\"} > 10)*32) - (sum((validator_balance{package=\"$package\"} offset 1d and validator_balance{package=\"$package\"} offset 1d > 10)) - count(validator_balance{package=\"$package\"} offset 1d > 10)*32)",
     "legendFormat": "Measured"
    }
   ]
  },
  {
   "title": "Weekly earnings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(validator_balance{package=\"$package\"}[1w])*3600*24*7)",
     "legendFormat": "Projected"
    },
    {
     "expr": "sum(delta(validator_balance{package=\"$package\"}[1w]))",
     "legendFormat": "Measured"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{package=\"$package\"} and validator_balance{package=\"$package\"} > 10) - count(validator_balance{package=\"$package\"} > 10)*32 - (sum((validator_balance{package=\"$package\"} offset 1d and validator_balance{package=\"$package\"} offset 1d > 10) or vector(0)) - (count(validator_balance{package=\"$package\"} offset 1d > 10) or vector(0))*32)"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((predict_linear(validator_balance{package=\"$package\"}[1h], 24*3600) and validator_statuses{package=\"$package\"}>2)) - sum(validator_balance{package=\"$package\"})"
    }
   ]
  },
  {
   "title": "Weekly",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{package=\"$package\"} and validator_balance{package=\"$package\"} > 10) - count(validator_balance{package=\"$package\"} > 10)*32 - (sum((validator_balance{package=\"$package\"} offset 1w and validator_balance{package=\"$package\"} offset 1w > 10) or vector(0)) - (count(validator_balance{package=\"$package\"} offset 1w > 10) or vector(0))*32)"
    }
   ]
  },
  {
   "title": "Weekly",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((predict_linear(validator_balance{package=\"$package\"}[1h], 7*24*3600) and validator_statuses{package=\"$package\"}>2)) - sum(validator_balance{package=\"$package\"})"
    }
   ]
  },
  {
   "title": "Monthly",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{package=\"$package\"} and validator_balance{package=\"$package\"} > 10) - count(validator_balance{package=\"$package\"} > 10)*32 - (sum((validator_balance{package=\"$package\"} offset 30d and validator_balance{package=\"$package\"} offset 1w > 10) or vector(0)) - (count(validator_balance{package=\"$package\"} offset 1w > 10) or vector(0))*32)"
    }
   ]
  },
  {
   "title": "Monthly",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((predict_linear(validator_balance{package=\"$package\"}[1h], 30*24*3600) and validator_statuses{package=\"$package\"}>2)) - sum(validator_balance{package=\"$package\"})"
    }
   ]
  },
  {
   "title": "Validator main info",
   "type": "table-old",
   "description": "This panel will count only the votes done since your validator process started",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_balance{package=\"$package\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_statuses{package=\"$package\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations{package=\"$package\"}) , \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_failed_attestations{package=\"$package\"})  , \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_successful_aggregations{package=\"$package\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_aggregations{package=\"$package\"}) , \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_successful_proposals{package=\"$package\"}) , \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_proposals{package=\"$package\"}) , \"pubkey_short\", \"$1\", \"pkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "Successful Attestations & Aggregations per hour",
   "type": "graph",
   "description": "Should be remain on the same level. On average 1 attestation per validator per epoch (12s * 32 slots = 384s).  So per validator we should see on avg 9.375 attestations per hour.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(validator_successful_attestations{package=\"$package\"}[3600s])*3600)",
     "legendFormat": "Attestations"
    },
    {
     "expr": "sum(rate(validator_successful_aggregations{package=\"$package\"}[3600s])*3600)",
     "legendFormat": "Aggregations"
    }
   ]
  },
  {
   "title": "BEACON / NETWORK",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "SERVER",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_voted_target_balances{package=\"$package\"}/total_eligible_balances{package=\"$package\"}",
     "legendFormat": "Participation rate"
    }
   ]
  },
  {
   "title": "Number of slot behind",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_clock_time_slot{package=\"$package\"}-beacon_head_slot{package=\"$package\"}"
    }
   ]
  },
  {
   "title": "Node process started",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 24 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{service=\"$service_beacon_chain\",package=\"$package\"})/3600"
    }
   ]
  },
  {
   "title": "Validator process started",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 24 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{service=\"$service_validator\",package=\"$package\"})/3600"
    }
   ]
  },
  {
   "title": "Alert: Number of slot behind",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_clock_time_slot{package=\"$package\"}-beacon_head_slot{package=\"$package\"}",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{package=\"$package\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Alert: Crashed",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(log_entries_total{level=\"fatal\",package=\"$package\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Peers connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",package=\"$package\"}"
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes", "label": "mem usage" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{package=\"$package\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Alert: Hourly earning <= 0",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(validator_balance{package=\"$package\"}[1h]))",
     "legendFormat": "validators balance on 1h"
    }
   ]
  },
  {
   "title": "Alert: More than 50 errors in 1h",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{service=\"$service_beacon_chain\", level=\"error\", package=\"$package\"}[1h]))",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(delta(log_entries_total{service=\"$service_beacon_chain\", level=\"warning\", package=\"$package\"}[1h]))",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Alert: Validator has been slashed",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_statuses{package=\"$package\"}, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Total balance all validators",
   "type": "graph",
   "description": "This graph is made for trading purpose mostly.\nSupposing that if a lot of validators are exiting, price is gonna dump.\n\nAlso this can prevent to exit while exiting queue is too long, same for depositing while pending queue is too long.\n\n",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\", package=\"$package\"} / 10e8",
     "legendFormat": "Active"
    },
    {
     "expr": "validators_total_balance{state=\"Pending\", package=\"$package\"} / 10e8",
     "legendFormat": "Pending"
    },
    {
     "expr": "validators_total_balance{state=\"Exiting\", package=\"$package\"} / 10e8",
     "legendFormat": "Exiting"
    }
   ]
  },
  {
   "title": "Hourly log type counter",
   "type": "bargauge",
   "description": "This panel won't have consistant values during the first hour of the node started process",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{service=\"$service_beacon_chain\", level=\"error\", package=\"$package\"}[1h]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(delta(log_entries_total{service=\"$service_beacon_chain\", level=\"warning\", package=\"$package\"}[1h]))",
     "legendFormat": "warning"
    }
   ]
  },
  {
   "title": "Alert: Less than 3 peers",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\", package=\"$package\"}"
    }
   ]
  }
 ]
}